### ISSUE TITLE
Subtitle color not respecting color requested within Kodi settings, for subtitle color?

### ISSUE THREAD

**Issue by Mike-KL** [rbuehlma/pvr.zattoo#140] opened 2022-03-01 18:32 UTC
As mentioned in this [kodi thread post](https://forum.kodi.tv/showthread.php?tid=364572&pid=3088847#pid3088847) with sample screengrabs and kodi.logs.  pvr.zattoo does not respect color of subtitles requested within Kodi Settings for subtitle color

rpi4 with Nightly LibreELEC 11 (Kodi 20.0) pvr.zattoo subtitles are always red
rpi3 with LibreELEC 9.2.3 (Kodi 18.9) pvr.zattoo subtitles are always white

I mentioned issue in particular Kodi thread above as subtitles are being rendered differently in Kodi 20 from earlier kodi versions and thought it worth raising "almost as a general query" surrounding how to ensure addons such as pvr.zatto (which receive subtitle info within stream) correctly use subtitle font and color user settings where/when appropriate.

CastagnaIT, requested debug log (which I provided) and made initial thoughts/observations on possible causes, requesting some sample raw subtitle data that pvr.zattoo receives and provides to Kodi?

**Comment by rbuehlma** [comment] 2022-03-01 19:50
This addon does not handle the stream itself. The addon passes the stream url to inputstream.adaptive which then fetches the actual data including the subtitles and provides the to Kodi. If the color of the subtitle is indeed affected by any addon, I would suggest to open a ticket there.

The fact that the color is different in Kodi 19 (there it is white as well) and Kodi 20, indicates that no color is set in the raw stream  from zattoo and inputstream.adaptive or Kodi is doing something different now.

**Comment by CastagnaIT** [comment] 2022-03-02 14:25
on kodi 20 colors are set only with subtitle tags,
but to try check what happens and where is the problem we need to check in order

ISAdaptive is used then in theory since Kodi detect the subs as SRT, the subtitle picked in ISA should be TTML format
to have a confirm of this is needed that someone attach here the MPD manifest of played video
so i can see what ISA parse

after this, is needed get a sample of raw data
maybe here i can try provide a custom build to try print in the log the subs raw data
but i need someone install it and OFC provide logs
(i can provide build only for Windows 10 64bit)

**Comment by rbuehlma** [comment] 2022-03-02 17:05
@CastagnaIT can you provide a patch to get the raw data? I will den apply that patch against Kodi 19 and provide you with the output. WIll that work?

**Comment by CastagnaIT** [comment] 2022-03-02 17:11
as mentioned in my previous comment, i cannot create a patch without know the subtitle format type specified in stream dash manifest, this because not all subtitles are handled in same way
so attach here the dash manifest

**Comment by rbuehlma** [comment] 2022-03-02 18:37
Here you are:

`<?xml version="1.0" encoding="UTF-8"?>
<MPD xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="urn:mpeg:dash:schema:mpd:2011"
 xmlns:scte35="urn:scte:scte35:2013:xml"
xsi:schemaLocation="urn:mpeg:dash:schema:mpd:2011 http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd"
 minBufferTime="PT1S"
 profiles="urn:mpeg:dash:profile:isoff-live:2011"
 type="dynamic"
 timeShiftBufferDepth="PT10800S"
 minimumUpdatePeriod="PT1.600S"
 publishTime="2022-03-02T18:35:28Z"
 availabilityStartTime="1970-01-01T00:00:00Z">
  <Period id="1" start="PT0S">
    <AdaptationSet id="0" mimeType="video/mp4" contentType="video" segmentAlignment="true" startWithSAP="1">
      <InbandEventStream schemeIdUri="https://zattoo.com/emsg/latency" value="live"/>
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="main"/>
      <SegmentTemplate media="f_track_video_ts_$Time$_nd_1600_d_1600_mbr_8000_bw_$Bandwidth$_num_0_tid_1.mp4?z32=MNZWSZB5GE3EIOCBGQYEGQSEG5BEIMJVIQWTINBWGM4UKOKGIQ3UENBVGFCEKJTVONSXEX3JMQ6TSNBTGE2SM5R5GATHG2LHHU4F6YJXGE4DQYZXME3TAMDBGFSTMOLFGRRDMMBXGE3GEZTBHBTDOYRQ" presentationTimeOffset="0" timescale="1000" initialization="i_track_video_nd_1600_d_1600_mbr_8000_bw_$Bandwidth$_num_0_tid_1.mp4?z32=MNZWSZB5GE3EIOCBGQYEGQSEG5BEIMJVIQWTINBWGM4UKOKGIQ3UENBVGFCEKJTVONSXEX3JMQ6TSNBTGE2SM5R5GATHG2LHHU4F6YJXGE4DQYZXME3TAMDBGFSTMOLFGRRDMMBXGE3GEZTBHBTDOYRQ" startNumber="1028897082">
        <SegmentTimeline>
          <S t="1646235329600" d="1600" r="6749"/>
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation id="0" bandwidth="7800000" width="1920" height="1080" codecs="avc1.4d402a" frameRate="50"/>
      <Representation id="1" bandwidth="4800000" width="1280" height="720" codecs="avc1.4d4020" frameRate="50"/>
      <Representation id="2" bandwidth="2800000" width="1280" height="720" codecs="avc1.4d401f" frameRate="25"/>
      <Representation id="3" bandwidth="1300000" width="768" height="432" codecs="avc1.4d401e" frameRate="25"/>
      <Representation id="4" bandwidth="700000" width="512" height="288" codecs="avc1.4d4015" frameRate="25"/>
      <Representation id="5" bandwidth="452000" width="512" height="288" codecs="avc1.4d4015" frameRate="25"/>
    </AdaptationSet>
    <AdaptationSet id="1" mimeType="audio/mp4" contentType="audio" lang="de" codecs="mp4a.40.2" segmentAlignment="true" startWithSAP="1">
      <AudioChannelConfiguration schemeIdUri="urn:mpeg:mpegB:cicp:ChannelConfiguration" value="2"/>
      <SegmentTemplate media="f_track_audio_ts_$Time$_nd_1600_mbr_8000_bw_$Bandwidth$_d_1600_num_0_tid_2_p_10_l_de.m4s?z32=MNZWSZB5GE3EIOCBGQYEGQSEG5BEIMJVIQWTINBWGM4UKOKGIQ3UENBVGFCEKJTVONSXEX3JMQ6TSNBTGE2SM5R5GATHG2LHHU4F6YJXGE4DQYZXME3TAMDBGFSTMOLFGRRDMMBXGE3GEZTBHBTDOYRQ" presentationTimeOffset="0" timescale="1000" initialization="i_track_audio_nd_1600_mbr_8000_bw_$Bandwidth$_d_1600_num_0_tid_2_p_10_l_de.mp4?z32=MNZWSZB5GE3EIOCBGQYEGQSEG5BEIMJVIQWTINBWGM4UKOKGIQ3UENBVGFCEKJTVONSXEX3JMQ6TSNBTGE2SM5R5GATHG2LHHU4F6YJXGE4DQYZXME3TAMDBGFSTMOLFGRRDMMBXGE3GEZTBHBTDOYRQ" startNumber="1028897082">
        <SegmentTimeline>
          <S t="1646235329600" d="1600" r="6749"/>
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation id="6" bandwidth="128000"/>
    </AdaptationSet>
    <AdaptationSet id="2" mimeType="audio/mp4" contentType="audio" lang="en" codecs="mp4a.40.2" segmentAlignment="true" startWithSAP="1">
      <AudioChannelConfiguration schemeIdUri="urn:mpeg:mpegB:cicp:ChannelConfiguration" value="2"/>
      <SegmentTemplate media="f_track_audio_ts_$Time$_nd_1600_mbr_8000_bw_$Bandwidth$_d_1600_num_2_tid_4_p_10_l_en.m4s?z32=MNZWSZB5GE3EIOCBGQYEGQSEG5BEIMJVIQWTINBWGM4UKOKGIQ3UENBVGFCEKJTVONSXEX3JMQ6TSNBTGE2SM5R5GATHG2LHHU4F6YJXGE4DQYZXME3TAMDBGFSTMOLFGRRDMMBXGE3GEZTBHBTDOYRQ" presentationTimeOffset="0" timescale="1000" initialization="i_track_audio_nd_1600_mbr_8000_bw_$Bandwidth$_d_1600_num_2_tid_4_p_10_l_en.mp4?z32=MNZWSZB5GE3EIOCBGQYEGQSEG5BEIMJVIQWTINBWGM4UKOKGIQ3UENBVGFCEKJTVONSXEX3JMQ6TSNBTGE2SM5R5GATHG2LHHU4F6YJXGE4DQYZXME3TAMDBGFSTMOLFGRRDMMBXGE3GEZTBHBTDOYRQ" startNumber="1028897082">
        <SegmentTimeline>
          <S t="1646235329600" d="1600" r="6749"/>
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation id="7" bandwidth="128000"/>
    </AdaptationSet>
    <AdaptationSet id="3" mimeType="application/mp4" contentType="text" lang="de" codecs="stpp">
      <Role schemeIdUri="urn:mpeg:dash:role:2011" value="alternate"/>
      <SegmentTemplate media="f_track_subs_ts_$Time$_bw_8000000_nd_1600_d_1600_mbr_8000_num_0_tid_5_l_de.m4s?z32=MNZWSZB5GE3EIOCBGQYEGQSEG5BEIMJVIQWTINBWGM4UKOKGIQ3UENBVGFCEKJTVONSXEX3JMQ6TSNBTGE2SM5R5GATHG2LHHU4F6YJXGE4DQYZXME3TAMDBGFSTMOLFGRRDMMBXGE3GEZTBHBTDOYRQ" presentationTimeOffset="0" timescale="1000" initialization="i_track_subs_bw_8000000_nd_1600_d_1600_mbr_8000_num_0_tid_5_l_de.mp4?z32=MNZWSZB5GE3EIOCBGQYEGQSEG5BEIMJVIQWTINBWGM4UKOKGIQ3UENBVGFCEKJTVONSXEX3JMQ6TSNBTGE2SM5R5GATHG2LHHU4F6YJXGE4DQYZXME3TAMDBGFSTMOLFGRRDMMBXGE3GEZTBHBTDOYRQ" startNumber="1028897082">
        <SegmentTimeline>
          <S t="1646235329600" d="1600" r="6749"/>
        </SegmentTimeline>
      </SegmentTemplate>
      <Representation id="8" bandwidth="100"/>
    </AdaptationSet>
  </Period>
</MPD>`

**Comment by CastagnaIT** [comment] 2022-03-03 10:29
Good then confirm that is TTML, these are the patches

ISAdaptive side (relative to Nexus branch):
https://github.com/CastagnaIT/inputstream.adaptive/commit/2b2bc0af0584ae8ef7ce9a52432a41fa58208f23
and Kodi side (relative to master branch):
https://github.com/CastagnaIT/xbmc/commit/df4373f536f9290f4380ef91773f9f7ae6c96d01

**Comment by rbuehlma** [comment] 2022-03-03 18:29
I'm still on Kodi 19 and can't apply these patches. Are you able to port them to Kodi 19?

**Comment by CastagnaIT** [comment] 2022-03-03 18:42
the red color "problem" is under Kodi 20
we cannot test on Kodi 19 because on Kodi 20 the subtitle management has been full reworked
if can be a option i can provide a build for Windows 64bit
but if nobody here can provide a log under Windows i cannot provide any further help
(or you can find some other dev that build for your system)

**Comment by Mike-KL** [comment] 2022-03-04 06:31
If i can be of help testing kodi 20 build with patches installed, happy to do so.  Able to run tests on Win64bit.

Is it just a matter of installing patched build and then run testing Zattoo streams with subtitles displayed with debugging (specific debug option?) enabled; to provide required information?

**Comment by CastagnaIT** [comment] 2022-03-04 07:56
good i will provide the patched builds soon with instructions
regular kodi debug setting enabled is enough, no need to enable also specifics settings

**Comment by CastagnaIT** [comment] 2022-03-04 08:37
Here, then
Open and extract the zip of Kodi20 in to a folder (like e.g. C:\Kodi20Test):
Kodi20: https://www.dropbox.com/s/86y69lm6laizqfu/KodiPortable_Builded_20_patchedSubsLog.zip?dl=1

Run Kodi 20 as portable, just run "_RunAsPortable.bat"

Then via addon kodi menu section, install the InputStreamAdaptive patched zip:
[inputstream.adaptive_patched.zip](https://github.com/rbuehlma/pvr.zattoo/files/8184255/inputstream.adaptive_patched.zip)

Remember to enable kodi debug and after reproduce the problem,
the log will be under the folder where you have extracted Kodi to subfolder `\portable_data\kodi.log`

**Comment by Mike-KL** [comment] 2022-03-04 17:25
Installation and test performed as suggested/requested, I confirm subtitle text displayed was color red with no settings modified in Kodi's settings.
[Kodi debug log](https://gist.githubusercontent.com/Mike-KL/e989efc1a08e5768259902b9192de816/raw/ecb82d41c233a05647dca8005aec516dab67cc98/gistfile1.txt)

**Comment by CastagnaIT** [comment] 2022-03-04 18:42
thanks this is a good log
i think to have all what i need for check,
i think to understand the problem, should be caused by ISAdaptive subtitle TTML parser that is incomplete

I will try to see if the fix not require much work,
because we have already planned in roadmap the creation of a TTML parser in Kodi core
and then the removal of the incomplete TTML parser in ISAdaptive
but i do not know when will be done because TTML is a complex format type and require much work to do so
i will let you know

**Comment by Mike-KL** [comment] 2022-03-04 22:07
Thanks for looking into issue, ready to assist with further testing, should fix be possible, understand explanation and dont expect quick fix to be added into nightly builds of Kodi 20.

**Comment by CastagnaIT** [comment] 2022-03-05 15:17
@Mike-KL now that i have investigated i have found the real cause will be fixed soon

**Comment by mediaminister** [comment] 2023-01-21 09:13
It's a pity this bug made it to Kodi 20. Every MPEG-DASH stream that contains colored TTML subtitles gets red subtitles now in Kodi 20.
I don't understand what the following code is doing with the hex color codes, but it also mixes up html color names:
https://github.com/xbmc/xbmc/blob/2e406d9956f9f64dbb4212b3eb53d9da2bf84858/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleTagSami.cpp#L138-L139
For instance:
yellow becomes FFllye
cyan becomes FFancy
white becomes FFitwh
I guess these two lines of code should be inside the if statement above? Or the length of `tagOptionValue` should be checked?

**Comment by CastagnaIT** [comment] 2023-01-21 10:04
this is a know regression for subtitles like srt, at least from my part,
with the old subtitle implementation, colours were managed hacked way by the GUI
but now we have to implement a right way to lookup to html css colors
there is a hack in the webvtt class to lookup color names
but to implement this in right way is required to rework how is managed resources in kodi core
and add a class to load and manage the colors resources
given the large amount of work done on subtitles and other things, there was no time to do it for Kodi 20

you see always red color because the subtitle rendering library do not recognize the color

feel free to open an Issue (on kodi repository) to keep track of the implementation problem to be resolved
and attach my feedback comment

**Comment by rbuehlma** [comment] 2023-03-23 12:27
This should be fixed with https://github.com/xbmc/xbmc/pull/22608

Closing this issue

**Closed as completed by rbuehlma** 2023-03-23 12:27 UTC
