### ISSUE TITLE
kodi freeze if you skip to current time

### ISSUE THREAD

**Issue by Mannshoch** [rbuehlma/pvr.zattoo#141] opened 2022-03-06 07:31 UTC
1. Choose a current running program.
2. Select it and play from beginning.
3. multible-skip further than the current time

result:
kodi freeze

**Comment by rbuehlma** [comment] 2022-03-06 09:58
Yes I can confirm this issue and I have created a patch for an older version of inputstream.adaptive:

https://github.com/xbmc/inputstream.adaptive/pull/30

Unfortunately, that patch does not work anymore with the current code version. In any case, this is something which needs to be fixed in inputstream.adaptive and not this addon. I therefore suggest to open a issue against inputstream.adaptive

**Comment by rbuehlma** [comment] 2022-04-01 22:01
Closing this issue since it has been reported here: https://github.com/xbmc/inputstream.adaptive/issues/828

**Closed as completed by rbuehlma** 2022-04-01 22:01 UTC
