### ISSUE TITLE
addon not working  version 18.1.23

### ISSUE THREAD

**Issue by irontes** [rbuehlma/pvr.zattoo#116] opened 2021-02-10 15:23 UTC
Windows 10
Kodi Leia
Zattoo PVR Addon
Version 18.1.23 latest update
The PVR is  loading the list but it is not playing

**Comment by irontes** [comment] 2021-02-10 15:46
I found the solution. in configuration in the option "Stream Type" the "hls" type does not work anymore , if I choose "dash" or "dash_widevine" it works.
What is the recommended configuration? dash or dash_widevine?
Thank you for the wonderful work you do

**Comment by olaflischke** [comment] 2021-02-13 16:20
Doesn't solve the problem with my Raspi 3/OSMC 2020.11 (freshly installed): Channel list stays empty, blue box with "Zattoo Client" and no message pops up when enabling addon.

**Comment by rbuehlma** [comment] 2021-02-13 22:00
To be able to analyze this issue, please provide a debug log.

**Comment by olaflischke** [comment] 2021-02-14 10:32
Here you go:
https://paste.osmc.tv/agiconecex

**Comment by Firewolf1337** [comment] 2021-02-14 13:03
Hi @olaflischke,
I had the same issue the past two days, with Libreelec 9.2.6 but now it seems to be solved, so i think it was a problem at Zattoo not the Plugin. In your log also seems that you are still on 18.1.21 not 18.1.23 maybe an update could help on your side.

**Comment by olaflischke** [comment] 2021-02-14 15:27
Silly question: How? Clicking "Update" on the addon in addon browser tells me "No updates avail". sudo apt-get update && sudo apt-get dist-upgrade tells me "0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded."

**Comment by Firewolf1337** [comment] 2021-02-14 16:35
In the LibreElec repository the lates version is 18.1.23.1. Maybe on OSMC the repo hasn't been updated yet,

**Comment by nicolasr75** [comment] 2021-02-15 09:07
Have the above mentioned problems all the same root? 
Some might be related to this https://github.com/rbuehlma/pvr.zattoo/issues/114

As you can see, this was fixed days ago but, at least for LibreElec, it took a few more days until it was approved by the team to be finally available in the addon repository. See https://github.com/LibreELEC/LibreELEC.tv/pull/5134

Also it might be necessary to manually update the repository or restart in LibreElec.

Anyway, yesterday my LibreElec automatically updated to version 18.1.23.1 and now it works again.

**Comment by olaflischke** [comment] 2021-02-15 10:01
Ok, switched to LibreELEC. Addon 18.1.23.1 available and working.

**Comment by rbuehlma** [comment] 2021-02-15 20:19
Closing this issue since the problem is solved in the addon. If some platforms required to update their addon repo, a ticket should be opened against them.

**Closed as completed by rbuehlma** 2021-02-15 20:19 UTC
