### ISSUE TITLE
Raspi: High CPU load and constantly loading from cache file

### ISSUE THREAD

**Issue by croneter** [rbuehlma/pvr.zattoo#65] opened 2019-12-16 20:19 UTC
Using a raspberry pi 3 with LibreElec 9.2.0 and Kodi 18.5. Right after boot, Zattoo seems to cause high CPU loads.
Anything you can do about that?    

[Full kodi.log](https://github.com/rbuehlma/pvr.zattoo/files/3969948/kodi.log)

Excerpts from the log:
```
2019-12-16 21:08:00.524 T:1395991424   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/2706a0bab5bd90a43561e5eec6b7048d].
2019-12-16 21:08:00.606 T:1429562240   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/3c16b77f6ac49a1ed48877464d11ae6a].
2019-12-16 21:08:00.681 T:1412776832   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/7c16091fb6e287952bb1f6747864ecd4].
2019-12-16 21:08:00.692 T:1404384128   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/78271ff164c312c56ed37332e2d7288d].
2019-12-16 21:08:00.716 T:1421169536   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/90f753248da57961f790ac4219350553].
2019-12-16 21:08:00.945 T:1395991424   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/a51c94853ea19ec7df0fdf93bc0a4089].
2019-12-16 21:08:01.036 T:1429562240   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/a3bed52c4e1bd46073f57a1441740103].
2019-12-16 21:08:01.053 T:1412776832   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/9b94123d4d6b7ea5c1cfbba7a7adaceb].
2019-12-16 21:08:01.107 T:1404384128   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/90f753248da57961f790ac4219350553].
2019-12-16 21:08:01.120 T:1421169536   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/62cd625070d826e3acd5eed362f5afcf].
2019-12-16 21:08:01.370 T:1395991424   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/3c16b77f6ac49a1ed48877464d11ae6a].
2019-12-16 21:08:01.436 T:1412776832   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/f34736ca9142cf0cd1db4fa82ca69ccd].
2019-12-16 21:08:01.451 T:1429562240   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/78271ff164c312c56ed37332e2d7288d].
2019-12-16 21:08:01.528 T:1404384128   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/62cd625070d826e3acd5eed362f5afcf].
2019-12-16 21:08:01.553 T:1421169536   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/e10597dc70a09af9684ae09268c99d98].
2019-12-16 21:08:01.879 T:1412776832   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/f14c7bfb2dcece4d4e27d4e257a8b609].
2019-12-16 21:08:01.899 T:1404384128   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/e10597dc70a09af9684ae09268c99d98].
2019-12-16 21:08:01.924 T:1429562240   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/90f753248da57961f790ac4219350553].
2019-12-16 21:08:01.983 T:1421169536   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/f4f3d02c65c89f53a64cbc0031a1dc4f].
2019-12-16 21:08:02.119 T:1395991424   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/78271ff164c312c56ed37332e2d7288d].
2019-12-16 21:08:02.272 T:1412776832   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/3a40d0fcae5a4fc2ff4986bb9ebfea76].
2019-12-16 21:08:02.292 T:1404384128   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file [special://profile/addon_data/pvr.zattoo/cache/f4f3d02c65c89f53a64cbc0031a1dc4f].
2019-12-16 21:08:02.356 T:1429562240   DEBUG: AddOnLog: Zattoo PVR Client: Load from cache file ```

**Comment by ksooo** [comment] 2019-12-16 20:35
Seems that at startup of the addon pvr.zattoo starts 5 threads that fire epg events in a tight loop against kodi. This keeps my 8 cores i7 busy at 500+% CPU load for about a minute (with the number of channels and epg data I have here). Not that cute if you ask me. 5 threads do not make sense at all because kodi does serialize the epg event pushes anyway. Lowering the thread's priority might help as well.

**Comment by croneter** [comment] 2019-12-16 20:41
Thanks for the quick reply. Anything I could do in my Ende?

**Comment by ksooo** [comment] 2019-12-16 20:42
Nothing.

**Comment by ksooo** [comment] 2019-12-16 20:43
<img width="1027" alt="Screenshot 2019-12-16 at 21 42 20" src="https://user-images.githubusercontent.com/3226626/70941551-0368ec80-204d-11ea-9ba3-52cfe5ed7aaf.png">
<img width="544" alt="Screenshot 2019-12-16 at 21 40 30" src="https://user-images.githubusercontent.com/3226626/70941559-0663dd00-204d-11ea-8516-416cfbe25e3f.png">

**Comment by croneter** [comment] 2019-12-16 20:43
Ouch

**Comment by rbuehlma** [comment] 2019-12-16 21:54
Its a feature... not a bug ;) Well, the goal is to load the epg as fast as possible. On my system, this takes less than 30 seconds (estimated, not measured) and does not really impact the useability (i can still start watching a channel while the epg is loading). The idea behind the 5 threads is to do the download in parallel. The EPG events are fired in serial against Kodi since Kodi seems to mess up if this is done in parallel.

Now what exactly is your issue? Ist the system unresponsive for this time?

What you can do:
Decrease the amount of EPG data which needs to be loaded either by lowering the number of channels or by reducing the time frame of EPG which is loaded.

What I can do: Provide a setting which allows you to specify the number of threads which are used. This will probably reduce the cpu load but it will then take longer for the epg to be loaded.

@ksooo Do you see another option to improve this? I am using Kodis' curl to download the guide data and CMutex to serialize transfering the data to Kodi.

**Comment by croneter** [comment] 2019-12-17 05:33
Many thanks!

I experienced stuttering playback on the raspi after startup for maybe 15min. Ill try and lower the epg data, though right now I'm using the "standard" kodinerds source, https://github.com/jnk22/kodinerds-iptv, with Zero tinkering

Other issue is PlexKodiConnect :cry: . With LibreElec 9.2 and Kodi 18.5, Kodi crashes on startup. I suspekt due to the number oft threads from both PKC and Zattoo. 18.2  was running fine though...

**Comment by rbuehlma** [comment] 2019-12-17 06:55
Sounds like you have a temperature issue with your PI. Do you have a PI 4? I've heard they need to have a cooling to prevent this.

In any case, I will add a setting for the number of threads unless @ksooo has a better suggestion.

**Comment by croneter** [comment] 2019-12-17 07:23
Nice, many thanks 😆 

Nope it's a Raspberry Pi 3 and it's definitely not a temperature issue. Maybe @ksooo also has an idea why 2 "thread-heavy" add-ons would cause Kodi to crash 😉

**Comment by rbuehlma** [comment] 2019-12-17 07:56
If its not a temperature issue, does it take 15 minutes to load all EPG data? Could you provide a full debug log for these 15 minutes? I would be interested in how long it takes to load the EPG.

**Comment by rbuehlma** [comment] 2019-12-19 07:41
In 18.1.10 the number of threads is now reduced to 3. Could you check if this improves the situation on your device?

**Comment by croneter** [comment] 2019-12-20 15:41
Thanks for the really quick help!! I'm rather busy now, sorry for that.

Silly question - do your updates show up more or less instantly on the Kodinerds repo?

**Comment by rbuehlma** [comment] 2019-12-20 15:44
I don't know how the Kodinerds repo is updated. As far as I know, this Addon is not even part of the Kodinerds repo.

**Comment by croneter** [comment] 2019-12-20 15:45
Silly me. I need to start documenting what I got from where :see_no_evil:

**Comment by rbuehlma** [comment] 2020-01-22 23:32
Closing this since issue should be solved.

**Closed as completed by rbuehlma** 2020-01-22 23:32 UTC

**Comment by croneter** [comment] 2020-01-23 05:37
Correct - has been working the last couple of weeks. Thanks a lot!


rbuehlma <notifications@github.com> schrieb am Do., 23. Jan. 2020, 00:32:
