### ISSUE TITLE
Crash changing channels

### ISSUE THREAD

**Issue by edenmedia** [rbuehlma/pvr.zattoo#191] opened 2023-08-25 17:11 UTC
I did a fresh install of Libreelec 11.03 then I installed only Zattoo Pvr.
When changing few channels it will crash and restart by it self.
This happens sometimes after just changing 2 or 3 channels other times it happens after about 10 - 15 channels, but in any case it always happens

LOG here: https://paste.kodi.tv/togugibati.kodi
Crash Log here: https://paste.kodi.tv/uzeditiqug.kodi

**Comment by numbernumero** [comment] 2023-08-25 17:29
same problems here

**Comment by rbuehlma** [comment] 2023-08-25 17:37
Closing this issue since it is a duplicate of https://github.com/rbuehlma/pvr.zattoo/issues/190. If required,you can open the original issue.

**Closed as completed by rbuehlma** 2023-08-25 17:37 UTC

**Comment by irontes** [comment] 2023-08-25 17:39
I have the same issue with LE Nexus. Using Windows and testing it, it seems that it works a bit better.
The problem of the PVR crash with inputstream is known to many users especially in Libreelec Nexus. We hope that the inputstream team will find a solution  (https://github.com/xbmc/inputstream.adaptive/issues/1362) otherwise we have to migrate to Android and use the related apps TV Mate, Zattoo etc.
