### ISSUE TITLE
PVR channels

### ISSUE THREAD

**Issue by retired-tired** [rbuehlma/pvr.zattoo#218] opened 2024-08-21 02:48 UTC
I have two Omega latest versions.  One is he Troy Point Fork the other is Kodi.   The Troy Point 21 Fork install has latest Diggz Xenon Plus installed, the Kodi Omega install has Big Kev's Aspire.   I use IPTV Merge and put my Add-Ons and M3U8 links, in Diggz I didn't need to because it's pre-populated.   Doesn't matter which install I watch, there are several that do NOT open that channel, instead they open a search box.  Does this mean my EPGs are bad?

**Comment by rbuehlma** [comment] 2024-08-21 07:15
I don't know your setup and used components and cannot support it. Can you try to reproduce the problem with a pure Kodi and if the problem happens there as well, add a debug log to this ticket.

There are some channels which do not work, but they should be labeled as "Unknown Channel". I will try to filter them out in a future update.

**Comment by retired-tired** [comment] 2024-08-21 16:07
I have a pretty good system.

 

BuzzTv X5 box.

 

I stayed up late last night and did a fresh install of Kodi with the Big Kev Aspire build, I have several M3U8 links and EPG links, it appears I was duplicating them.  I made both installs are using different links and the Aspire build seems to be working correctly (for now).

 

I’m a retired Technical Specialist with almost a 50-year background.  While this is a little different than what I specialize at, it is very similar.

 

I just needed someone like you to put a fire under my butt and take a closer look at what I had!   I appreciate your assistance.

 

Take care and enjoy!

Denny

**Comment by ksooo** [comment] 2024-08-21 16:53
> "Big Kev Aspire build", "Troy Point Fork", "Diggz Xenon Plus"

If you need support, go and ask the provider of these builds, nothing that is supported by the Kodi community. We do not support media piracy.

**Comment by retired-tired** [comment] 2024-08-21 17:00
I got it straightened out last night.

 

Fresh Kodi install, fresh Big Kev install and different links for IPTV merge.  All is right in my KODI world today!

 

Thank you

Take care and enjoy!

Denny

**Comment by rbuehlma** [comment] 2024-08-21 18:09
Closing issue since its not related to the addon and already solved.

**Closed as completed by rbuehlma** 2024-08-21 18:09 UTC
