### ISSUE TITLE
PVR client fails to authenticate

### ISSUE THREAD

**Issue by jfkotw** [rbuehlma/pvr.zattoo#83] opened 2020-04-10 13:41 UTC
The last couple of days the Zattoo PVR client no longer works for me. Relevant logs follow. From an issue in another Zattoo app, it seems like there is [a simple fix in the URL](https://github.com/nancpasc/ZattooBox/issues/40) required.

```
2020-04-10 14:03:00.092 T:2862732144  NOTICE: AddOnLog: Zattoo PVR Client: Using useragent: Kodi/18.5 pvr.zattoo/18.1.14 (Kodi PVR addon)
2020-04-10 14:03:00.108 T:2862732144   ERROR: CCurlFile::FillBuffer - Failed: Couldn't resolve host name(6)                       
2020-04-10 14:03:00.108 T:2862732144   ERROR: CCurlFile::Open failed with code 0 for https://zattoo.com/:                         
2020-04-10 14:03:00.110 T:2862732144  NOTICE: AddOnLog: Zattoo PVR Client: Could not get app token from page. Try to load from file.
2020-04-10 14:03:05.294 T:2862732144   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403                             
2020-04-10 14:03:05.298 T:2862732144   ERROR: CCurlFile::Open failed with code 403 for https://zattoo.com/zapi/session/hello:     
2020-04-10 14:03:05.298 T:2862732144  NOTICE: AddOnLog: Zattoo PVR Client: Hello failed.                                          
2020-04-10 14:03:05.331 T:2862732144   ERROR: CCurlFile::FillBuffer - Failed: HTTP returned error 403                             
2020-04-10 14:03:05.331 T:2862732144   ERROR: CCurlFile::Open failed with code 403 for https://zattoo.com/zapi/v2/account/login:  
2020-04-10 14:03:05.331 T:2862732144   ERROR: AddOnLog: Zattoo PVR Client: Login failed. 
```

**Comment by rbuehlma** [comment] 2020-04-10 14:19
This is a duplicate of https://github.com/rbuehlma/pvr.zattoo/issues/81 which is already fixed :) If your Kodi distro has not updated the addon yet, you might find some user-built versions here:

https://www.kodinerds.net/index.php/Thread/58635-PVR-Addon-f%C3%BCr-Zattoo-und-Reseller/?postID=413272#post413272

**Closed as completed by rbuehlma** 2020-04-10 14:19 UTC
