### ISSUE TITLE
Flickering issue in LibreELEC 11.0.1 (Nexus)

### ISSUE THREAD

**Issue by numbernumero** [rbuehlma/pvr.zattoo#185] opened 2023-07-18 11:59 UTC
Hi as you mentioned earlier there is no more support for Kodi Matrix (too bad because in Matrix the operation was much smoother). In Libreelec Nexus (11.0.1) there are flickering problems in the first seconds when the channel starts and if you change the channels repeatedly with an interval of a few seconds after a while kodi (LibreELEC) freezes and starts again by itself

**Comment by rbuehlma** [comment] 2023-07-18 12:08
The flickering could be the resolution switch done by Kodi to match the screen resolution with the stream. You can try to disable this switching in the settings of Kodi.

The purpose of the restart is unclear to meh. Please provide a crash log created by Kodi during the crash. This should help to analyze this case.

**Comment by numbernumero** [comment] 2023-07-18 12:24
I'm not sure I understand which setting you're referring to. Maybe "Adjust display refresh rate"? in this case is disabled  and also disabled "Delay after change of refresh rate"

**Comment by codingPF** [comment] 2023-07-18 16:57
Adding a delay of 250ms increased stability and reduces freezing screen for me - maybe you give it a try.

**Comment by numbernumero** [comment] 2023-07-19 09:43
I tried as you suggested but unfortunately nothing changed.

**Comment by codingPF** [comment] 2023-07-19 18:31
Maybe this one will help on your issue #182

**Comment by numbernumero** [comment] 2023-07-21 08:39
> The flickering could be the resolution switch done by Kodi to match the screen resolution with the stream. You can try to disable this switching in the settings of Kodi.
> 
> The purpose of the restart is unclear to meh. Please provide a crash log created by Kodi during the crash. This should help to analyze this case.

@rbuehlma:
Ok I did a new installation of the last LibreELEC 11.0.3 I installed Zattoo PVR Client (20.3.11.1 the only one available in the repository) and after changing some channel Libreelec crashes and restarts by itself.
The problems of flickering are also present in this latest version of Libreelec
here the crash log of kodi : https://easyupload.io/9iohf0

**Comment by rbuehlma** [comment] 2023-07-21 08:56
The crash happens in inputstream.adaptive. You might want to open a bug report against that addon.

For the flickering: The cause is unclear to me there. Does it only happen with this PVR addon or also with other streams like movies? What if you are using e.g. the youtube addon?

This addon does not handle any stream data but only provides an url to inputstream.adaptive. I don't expect the flickering to be cause by this addon. My main suspects would be LibreELEC or Kodi together with your current hardware.

You could try to install a different Linux with Kodi (e.g. Ubuntu) and see if the flickering happens there as well.

And could you post a video of the flickering?

**Comment by numbernumero** [comment] 2023-07-21 09:02
Hi, the flickering is only with this Zattoo PVR Client and also with Simple PVR Client not with Youtube or other video addons. The crash happen only with Zattoo PVR Client not with Simple PVR Client.
About the flickering I opened an issue in LibreELEC Github.
I hope I explained myself well about the crash. Crashes happen only with Zattoo PVR when I change channels. Sometimes it happens after I changed 2-3 channels other times after I changed 10 channels repeatedly

**Comment by numbernumero** [comment] 2023-07-21 09:18
> The crash happens in inputstream.adaptive. You might want to open a bug report against that addon.
> 
> For the flickering: The cause is unclear to me there. Does it only happen with this PVR addon or also with other streams like movies? What if you are using e.g. the youtube addon?
> 
> This addon does not handle any stream data but only provides an url to inputstream.adaptive. I don't expect the flickering to be cause by this addon. My main suspects would be LibreELEC or Kodi together with your current hardware.
> 
> You could try to install a different Linux with Kodi (e.g. Ubuntu) and see if the flickering happens there as well.
> 
> And could you post a video of the flickering?

If it weren't for the fact that in The Matrix, Zattoo pvr doesn't always load the list, I would always be in the Matrix. there at least everything was smooth and very fast in zapping without crashes or artifacts.  
Just a question: there is something I could change in the version of Matrix to make Zattoo PVR load always without needing to restart every time?

**Comment by numbernumero** [comment] 2023-07-21 12:22
@rbuehlma
Like you suggested I opened a issue on https://github.com/xbmc/inputstream.adaptive/issues/1334.

**Comment by irontes** [comment] 2023-08-25 19:08
A new issue has been opened on Inputstream GitHub whose is much more detailed so I think it is better to refer to this one (https://github.com/xbmc/inputstream.adaptive/issues/1362)

**Comment by edenmedia** [comment] 2023-09-03 19:22
@rbuehlma Could you please take a look at the comments in this issue? https://github.com/xbmc/inputstream.adaptive/issues/1362

**Comment by rbuehlma** [comment] 2023-09-03 20:46
I've read the latest few comments, but not sure what exactly you want me to look at.

**Comment by edenmedia** [comment] 2023-09-03 22:13
Hi @rbuehlma  the problem of the crash in the PVR with Libreelec Nexus and Omega does not seem to have a solution in the short term so the only solution in the immediate would be to downgrade to Matrix. But unfortunately in Matrix addon like yours "Zattoo PVR" is no longer updated in fact the problems like this issue  https://github.com/rbuehlma/pvr.zattoo/issues/183 are always present.
It would be helpful to at least fix this problem in the Matrix version so that users using Zattoo PVR In Libreelec can solve the problem by downgrading from Libreelec Nexus to libreelec Matrix

**Comment by rbuehlma** [comment] 2023-09-10 19:30
I currently don't have the time to do this backport. But it's an opensource project. Anyone is welcome to submit a change.

**Comment by rbuehlma** [comment] 2024-08-19 14:41
Issue seems to be solved in Omega. Closing this ticket.

**Closed as completed by rbuehlma** 2024-08-19 14:41 UTC
