### ISSUE TITLE
Replay does not work anymore.

### ISSUE THREAD

**Issue by goggle** [rbuehlma/pvr.zattoo#23] opened 2018-07-06 16:23 UTC
I'm using pvr.zattoo in the LibreElec Testbuilds for Kodi 18 on a Raspberry Pi. I'm using a Zattoo partner and can watch all the shows for the last 7 days in "Replay" in the browser. Unfortunately, it does not work anymore in Kodi: When I open the TV guide in pvr.zattoo and select a show, there was a button called "Play program" or something similar. Now there is only a button "Switch", which will me redirect to live tv, but not play the selected show.

I'm wondering if this has something to do with the changes made in pvr.zattoo, or if it is related to changes made in the core of Kodi?

**Comment by rbuehlma** [comment] 2018-07-06 16:34
Probably its a change done by Zattoo itself. But nothing I can do without further information (debug log)

**Comment by goggle** [comment] 2018-07-07 03:04
Unfortunately I did not find anything regarding pvr.zattoo in the logfile `kodi.log`. If there is a way to enable debug logging, let me know. 

This is what Kodi is showing when I select a previously emitted show:
![imag0607](https://user-images.githubusercontent.com/1856425/42406194-dcebf7b8-81a2-11e8-80c9-b973a030316f.jpg)

2 months ago, there was a fourth button called "Play program" which allowed me to actually watch this show. Now, the button has disappeared.

Are you sure that no recent changes (in the month of June) could be the source for this issue? Do you see this button "Play program" in your setup?

**Comment by rbuehlma** [comment] 2018-07-07 08:09
I use this replay button all the time with the current nigthly builds. It works for me.

I'm not sure what the source of the problem is but as the current version of the addon and Kodi does work for me, i suspect that it is related to your Zattoo reseller.

Without a debug log there is not much i can do. And if there is nothing Zattoo related in the log, you are either not using pvr.zattoo or you are not looking into the Kodi logfile.

**Comment by goggle** [comment] 2018-07-07 10:17
Ok, I've booted Kodi, started a TV channel, opened the TV guide and selected an older show; here is what I get in the log file:
```
13:11:54.807 T:1939374912  NOTICE: ADDON: pvr.zattoo v999.18.0.50 installed
12:06:42.570 T:1459503984  NOTICE: AddOnLog: Zattoo PVR Client: Using useragent: Kodi/18.0 pvr.zattoo/18.0.50 (Kodi PVR addon)
12:06:42.932 T:1459503984  NOTICE: AddOnLog: Zattoo PVR Client: Got new beaker.session.id: 5d647..
12:06:42.980 T:1459503984  NOTICE: AddOnLog: Zattoo PVR Client: Got new beaker.session.id: 0e09d..
12:06:42.981 T:1459503984  NOTICE: AddOnLog: Zattoo PVR Client: Country code: CH
12:06:42.981 T:1459503984  NOTICE: AddOnLog: Zattoo PVR Client: Service region country: CH
12:06:42.981 T:1459503984  NOTICE: AddOnLog: Zattoo PVR Client: Stream type: hls
12:06:42.981 T:1459503984  NOTICE: AddOnLog: Zattoo PVR Client: Recall is disabled
12:06:42.981 T:1459503984  NOTICE: AddOnLog: Zattoo PVR Client: Selective recall is disabled
12:06:42.981 T:1459503984  NOTICE: AddOnLog: Zattoo PVR Client: Recordings are disabled
12:06:43.018 T:1459503984  NOTICE: AddOnLog: Zattoo PVR Client: Got new beaker.session.id: 6ab84..
12:06:43.093 T:1459503984  NOTICE: PVR Manager: Starting
12:06:44.973 T:1368154992  NOTICE: PVR Manager: Started
12:06:55.887 T:1384940400  NOTICE: AddOnLog: Zattoo PVR Client: Missing category: Home Improvement
12:07:55.695 T:1939374912  NOTICE: AddOnLog: Zattoo PVR Client: Got new beaker.session.id: 2382d..
12:07:55.748 T:1939374912  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/All channels/pvr.zattoo_1408026926.pvr
12:08:57.532 T:1939374912  NOTICE: AddOnLog: Zattoo PVR Client: Got new beaker.session.id: 90cc8..
12:08:57.556 T:1939374912  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/All channels/pvr.zattoo_442127252.pvr
12:09:00.934 T:1939374912  NOTICE: AddOnLog: Zattoo PVR Client: Got new beaker.session.id: 28a46..
12:09:00.969 T:1939374912  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/All channels/pvr.zattoo_136260.pvr
12:09:02.591 T:1939374912  NOTICE: AddOnLog: Zattoo PVR Client: Got new beaker.session.id: 28647..
12:09:02.618 T:1939374912  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/All channels/pvr.zattoo_109495.pvr
12:09:03.658 T:1939374912  NOTICE: AddOnLog: Zattoo PVR Client: Got new beaker.session.id: 983f9..
12:09:03.660 T:1939374912  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/All channels/pvr.zattoo_4245368.pvr
12:09:05.039 T:1939374912  NOTICE: AddOnLog: Zattoo PVR Client: Got new beaker.session.id: 78468..
12:09:05.082 T:1939374912  NOTICE: VideoPlayer::OpenFile: pvr://channels/tv/All channels/pvr.zattoo_4245367.pvr
```

Here is the whole log file:
[kodi.log](https://github.com/rbuehlma/pvr.zattoo/files/2172653/kodi.log)

**Comment by goggle** [comment] 2018-07-07 10:41
Ah ok, thanks, now it's working again! I switched to HLS because switching TV channels is notably faster with HLS than DASH.

May I ask why playing HLS streams for replay shows aren't supported? I'm the author of the Zattoo information extractor in [youtube-dl](https://github.com/rg3/youtube-dl), and I can tell, that there are definitely HLS streams for replay shows available.

**Comment by rbuehlma** [comment] 2018-07-07 11:29
I'm not sure if this was a limitation of the hls implementation in Kodi 17 or earlier in Zattoo itself but you are right, it also works for hls streams now. I have updated the addon. It should come with the next release. Thanks for the input.

Out of curiosity: How much is "notably faster with HLS"? The DASH stream starts for me within about half a second. The HLS stream feels about the same.

**Comment by goggle** [comment] 2018-07-07 13:01
Oh wow thanks, I will try it out as soon as the new build is ready!

It's hard to measure the channel switching times exactly, but let's say it takes 0.5 seconds to switch from one channel to another on HLS streaming, then it takes maybe 1 second to switch on DASH streaming. Furthermore, when using DASH streaming it takes some additional time (maybe 0.5 seconds) until the audio starts playing. This was the reason why I switched from DASH to HLS, but the user experience on DASH streaming is still quite good, it's totally usable, no worries.

**Comment by rbuehlma** [comment] 2018-07-07 16:47
Great, yes, less than 2 seconds is probably fine. I will close this issue as it should be fixed. Thanks.

**Closed** 2018-07-07 16:48 UTC
