### ISSUE TITLE
Since some days: replay and recording do not play on some channels

### ISSUE THREAD

**Issue by Mannshoch** [rbuehlma/pvr.zattoo#70] opened 2020-01-22 19:25 UTC
Since some days: replay and recording do not play on some channels. No message appear, simply nothing happens.
On this channels I have to add a recording on zattoo website and start the recorded show from kodi.

**Comment by rbuehlma** [comment] 2020-01-22 23:38
Closing this due to not enough information. Feel free to re-open the issue with additional information.

**Comment by Mannshoch** [comment] 2020-01-23 13:28
[kodi.zip](https://github.com/rbuehlma/pvr.zattoo/files/4103271/kodi.zip)

**Comment by rbuehlma** [comment] 2020-01-23 19:10
Could you let me know which show on which channel you tried to watch with replay?

**Comment by Mannshoch** [comment] 2020-01-23 19:15
"Mord ist ihr Hobby" on "Sat.1 Gold HD"

**Comment by rbuehlma** [comment] 2020-01-23 22:33
I could reproduce this error and will try to find the root cause.

**Comment by rbuehlma** [comment] 2020-01-24 19:24
This was a problem in the EPG service and should be solved now. As soons as you EPG gets updated, replay and recording should work.

**Closed as completed by rbuehlma** 2020-01-24 19:24 UTC

**Comment by Mannshoch** [comment] 2020-01-26 13:02
Was that an error you had to report to zattoo?

**Comment by rbuehlma** [comment] 2020-01-26 13:05
The problem was in the alternative EPG service not on Zattoo side.

**Comment by Mannshoch** [comment] 2020-01-26 13:07
Ah interesting, I thought that your app use also Zattoo for the EPG service.

**Comment by rbuehlma** [comment] 2020-01-26 13:10
By default it does, but you can activate the "Enhanced EPG service" which collects the data from Zattoo and then provides this data to Kodi in a more efficient way. This is the service I am running. For both cases the original EPG source is Zattoo.
