### ISSUE TITLE
Kodi Nexus Fire TV Stick 4k Max, crash after installing Zattoo 

### ISSUE THREAD

**Issue by gsicilia82** [rbuehlma/pvr.zattoo#160] opened 2023-01-16 22:58 UTC
Hi, today I wanted to try Kodi Nexus with Zattoo addon. I started with clear Kodi installation. After installing Zattoo and its autostart, Kodi crashs. After Kodi restart, it crashs immediately. After few attempts, always after Kodi data reset, it was possible to enter login credentials. But also in this case, Kodi crashs after click on ok button.
I wanted to create some log files. Hopefully the will help to find the issue

Kodi.old.log = first Kodi start with Zattoo install procedure 
Kodi.log = restart Kodi after crash 

Thank you for your time. 

[kodi.log](https://github.com/rbuehlma/pvr.zattoo/files/10429845/kodi.log)
[kodi.old.log](https://github.com/rbuehlma/pvr.zattoo/files/10429846/kodi.old.log)

**Comment by rbuehlma** [comment] 2023-01-16 23:02
Unfortunately, the log does not contain any usable information. Could you please try to create a crash log

**Comment by gsicilia82** [comment] 2023-01-17 07:31
Thanks for your fast feedback. I could not find any crash dedicated information. Do you mean a config in advancedsettings.xml? It seems to create same log as created over GUI settings. 

https://kodi.wiki/view/Log_file/Advanced

**Comment by gsicilia82** [comment] 2023-01-17 07:41
Hi, I cannot find any crashlog dedicated information. I have seen how to enable logging within advancedsettings.xml, but it would be the same as created with GUI settings.
I found old forum post, that crashlogs should be created automatically inside user folder. But I don't find any log files inside my user folder. Maybe you can give me a hint, how to create or how to find the specified crashlog?

Thanks

**Comment by rbuehlma** [comment] 2023-01-17 10:05
I have created an issue against Kodi: https://github.com/xbmc/xbmc/issues/22495

Closing this issue since it is a duplicate of https://github.com/rbuehlma/pvr.zattoo/issues/158

**Closed as completed by rbuehlma** 2023-01-17 10:05 UTC
