### ISSUE TITLE
Zattoo PVR Client: Unable to get app token.

### ISSUE THREAD

**Issue by olaflischke** [rbuehlma/pvr.zattoo#85] opened 2020-04-15 15:43 UTC
Zattoo PVR Client doesn't show any channels, shows empty blue banner (titled 'Zatto PVR Client') on startup or activating.
Log says:
```
2020-04-15 17:18:15.700 T:1763173088  NOTICE: AddOnLog: Zattoo PVR Client: Using useragent: Kodi/18.6 pvr.zattoo/18.1.14 (Kodi PVR addon)
2020-04-15 17:18:16.017 T:1763173088   ERROR: AddOnLog: Zattoo PVR Client: Unable to get app token.
...
2020-04-15 17:21:16.461 T:1577128672   ERROR: GetChannelGroups: PVR client 'Zattoo PVR Add-on:connected' returned an error: server error
2020-04-15 17:21:16.462 T:1577128672   ERROR: GetChannels: PVR client 'Zattoo PVR Add-on:connected' returned an error: server error
2020-04-15 17:21:16.462 T:1577128672   ERROR: GetChannelGroups: PVR client 'Zattoo PVR Add-on:connected' returned an error: server error
```

OSMC 2020.03-1, built-in Zattoo PVR Client, free Zattoo account

**Comment by rbuehlma** [comment] 2020-04-15 17:00
This is a duplicate of #81 which is already fixed :) If your Kodi distro has not updated the addon yet, you might find some user-built versions here:

https://www.kodinerds.net/index.php/Thread/58635-PVR-Addon-f%C3%BCr-Zattoo-und-Reseller/?postID=413272#post413272

**Closed as completed by rbuehlma** 2020-04-15 17:00 UTC
